name: validation

on:
  push:
    paths:
      - metrics/*
  workflow_dispatch:

jobs:
  validate:
    name: "metrics"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Verify that all files under /metrics are valid according to metrics/schema.json
        run: echo "TODO"
